export const CSV_COLUMNS = {
  player: 'Player',
  date: 'Date',
  total_distance: 'Total Distance (m)',
  zone1_distance: 'Distance speed zone 1 (m) (speed < 0.19m/s)',
  zone2_distance: 'Distance speed zone 2 (m) (0.19m/s ≤ speed < 2.00m/s)',
  zone3_distance: 'Distance speed zone 3 (m) (2.00m/s ≤ speed < 4.00m/s)',
  zone4_distance: 'Distance speed zone 4 (m) (4.00m/s ≤ speed < 5.50m/s)',
  zone5_distance: 'Distance speed zone 5 (m) (speed ≥ 5.50m/s)',
  zone3plus4plus5: 'Distance(3+4+5) (m) (speed ≥ 2.00m/s)',
  zone4plus5: 'Distance(4+5) (m) (speed ≥ 4.00m/s)',
  hmld: 'HMLD (m) (MetPow > 25.5W/kg)',
  hml_time: 'HML Time (mm:ss) (MetPow > 25.5W/kg)',
  high_efforts: 'High Efforts (MetPow > 25.5W/kg)',
  total_nrg: 'Total NRG expenditure (J/kg)',
  nrg_above_th: 'NRG expenditure above TH (J/kg)',
  equivalent_distance: 'Equivalent distance (m)',
  acc1: 'Accelerations 1 (2.0m/s² < accel ≤ 3.0m/s² and time ≥ 0.5s)',
  acc2: 'Accelerations 2 (3.0m/s² < accel ≤ 4.0m/s² and time ≥ 0.5s)',
  acc3: 'Accelerations 3 (accel > 4.0m/s² and time ≥ 0.5s)',
  dec1: 'Decelerations 1 (-2.0m/s² > accel ≥ -3.0m/s² and time ≥ 0.5s)',
  dec2: 'Decelerations 2 (-3.0m/s² > accel ≥ -4.0m/s² and time ≥ 0.5s)',
  dec3: 'Decelerations 3 (accel < -4.0m/s² and time ≥ 0.5s)',
  acc_2plus3: 'Accelerations (2+3) (accel > 3.0m/s² and time ≥ 0.5s)',
  dec_2plus3: 'Decelerations (2+3) (accel < -3.0m/s² and time ≥ 0.5s)',
  total_acc: 'Total Accelerations (accel > 2.0m/s² and time ≥ 0.5s)',
  total_dec: 'Total Decelerations (accel < -2.0m/s² and time ≥ 0.5s)',
  left_turns: 'Left turns (speed > 2.50m/s and angle ≤ -30° and time ≥ 0.5s)',
  right_turns: 'Right turns (speed > 2.50m/s and angle ≥ 30° and time ≥ 0.5s)',
  avg_metabolic: 'Average metabolic power (W/kg)',
  max_metabolic: 'Max metabolic power (W/kg)',
  top_speed: 'Top speed (km/h)',
  avg_speed: 'Average speed (km/h)',
  avg_hr: 'Average HR (bpm)',
  max_hr: 'Maximum HR (bpm)',
  heart_exertion: 'Heart exertion',
  heart_exertion_th: 'Heart exertion above TH',
  intensity_indicator: 'Intensity indicator',
  workload_index: 'Work load index',
  hr_zone1: 'HR zone 1 (mm:ss) (HR ≤ 120)',
  hr_zone2: 'HR zone 2 (mm:ss) (120 < HR ≤ 140)',
  hr_zone3: 'HR zone 3 (mm:ss) (140 < HR ≤ 160)',
  hr_zone4: 'HR zone 4 (mm:ss) (160 < HR ≤ 180)',
  hr_zone5: 'HR zone 5 (mm:ss) (HR > 180)',
  avg_hr_bpm: 'Average HR (bpm)',
  max_hr_bpm: 'Maximum HR (bpm)',
}
