export const CSV_COLUMNS = {
  player: 'Player',
  date: 'Date',
  total_distance: 'Total Distance (m)',
  zone1_distance: 'Distance speed zone 1 (m)',
  zone2_distance: 'Distance speed zone 2 (m)',
  zone3_distance: 'Distance speed zone 3 (m)',
  zone4_distance: 'Distance speed zone 4 (m)',
  zone5_distance: 'Distance speed zone 5 (m)',
  zone3plus4plus5: 'Distance(3+4+5) (m)',
  zone4plus5: 'Distance(4+5) (m)',
  hmld: 'HMLD (m) (MetPow > 25.5W/kg)',
  hml_time: 'HML Time (mm:ss) (MetPow > 25.5W/kg)',
  high_efforts: 'High Efforts (MetPow > 25.5W/kg)',
  total_nrg: 'Total NRG expenditure (J/kg)',
  nrg_above_th: 'NRG expenditure above TH (J/kg)',
  equivalent_distance: 'Equivalent distance (m)',
  acc1: 'Accelerations 1',
  acc2: 'Accelerations 2',
  acc3: 'Accelerations 3',
  dec1: 'Decelerations 1',
  dec2: 'Decelerations 2',
  dec3: 'Decelerations 3',
  acc_2plus3: 'Accelerations (2+3)',
  dec_2plus3: 'Decelerations (2+3)',
  total_acc: 'Total Accelerations',
  total_dec: 'Total Decelerations',
  left_turns: 'Left turns',
  right_turns: 'Right turns',
  avg_metabolic: 'Average metabolic power (W/kg)',
  max_metabolic: 'Max metabolic power (W/kg)',
  top_speed: 'Top speed',
  avg_speed: 'Average speed',
  avg_hr: 'Average HR (bpm)',
  max_hr: 'Maximum HR (bpm)',
  heart_exertion: 'Heart exertion',
  heart_exertion_th: 'Heart exertion above TH',
  intensity_indicator: 'Intensity indicator',
  workload_index: 'Work load index',
  hr_zone1: 'HR zone 1',
  hr_zone2: 'HR zone 2',
  hr_zone3: 'HR zone 3',
  hr_zone4: 'HR zone 4',
  hr_zone5: 'HR zone 5',
}
